version: "3.8"
services:
  database:
    image: mongo
    restart: always
    container_name: database
    ports:
      - "27017:27017"
    environment:
      - DB_URL=mongodb://database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    container_name: weather-app-backend
    networks:
      - weather-app-network
    environment:
      - db=weather-db
      - db_port=27017

  dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

networks:
  weather-app-network:
    driver: bridge
