version: "3.8"
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    container_name: mongodb
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    container_name: weather-app-backend
    networks:
      - app-network

  dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    container_name: frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


